---
- name: Install packages
  apt: name={{ item }}
  with_items:
    - libmagickcore-dev
    - libmagickwand-dev
    - libmagick++-dev
    - libdjvulibre-dev
    - libjpeg-dev
    - libtiff-dev
    - libwmf-dev

- name: Install rmagick gem
  command: bash -lc "gem install rmagick"
  sudo_user: '{{ user_name }}'