---
vm_swap: 512

use_apt_proxy: false

# Additional packages
packages:
  - curl
  - libcurl3
  - libcurl3-gnutls
  - libcurl4-openssl-dev
  - libmagickcore-dev
  - libmagickwand-dev
  - libmagick++-dev
  - libsqlite3-dev

# Server config
server_name: localhost
user_name: vagrant
group_name: vagrant
user_home_path: '/home/{{ user_name }}'

rbenv_path: '{{ user_home_path }}/.rbenv'
rbenv_bin: '{{ rbenv_path }}/bin/rbenv'

# Ruby and Rails
rails_version: '~> 4.2'
ruby_version: 2.2.0
environment_file: /vagrant/.envrc

#MySQL
mysql_db_name: myapp
mysql_db_user: '{{user_name}}'
mysql_db_password: 123456
